server:
  servlet:
    context-path: /api

spring:
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/cooking?useUnicode=true&characterEncoding=UTF8
#    username: postgres
#    password: postgres
#  jpa:
#    show-sql: true
  h2:
    console.enabled: true
    console:
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:cooking
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  liquibase:
    change-log: classpath:liquibase/master.xml
    enabled: true

logging:
  level:
    com.cooking.api: DEBUG

