CREATE TABLE IF NOT EXISTS recipe (
    id UUID UNIQUE  NOT NULL CONSTRAINT PK_recipe PRIMARY KEY,
    vegetarian BOOLEAN NOT NULL DEFAULT FALSE,
    serving_amount INTEGER NOT NULL DEFAULT 1,
    name VARCHAR(255) UNIQUE NOT NULL,
    instruction TEXT
);